[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[phases.start]
cmd = "python bot.py"

[phases.preDeploy]
cmds = [". .venv/bin/activate"]
